#!/bin/sh
./GameBoy BROKER CAUGHT_POKEMON 1 OK
./GameBoy BROKER CAUGHT_POKEMON 2 FAIL

./GameBoy BROKER NEW_POKEMON Pikachu 2 3 1

./GameBoy BROKER CATCH_POKEMON Onix 4 5

./GameBoy SUSCRIPTOR NEW_POKEMON 10

./GameBoy BROKER CATCH_POKEMON Charmander 4 5
