#!/bin/sh
./GameBoy BROKER CAUGHT_POKEMON 1 OK
./GameBoy BROKER CAUGHT_POKEMON 2 FAIL

./GameBoy BROKER CATCH_POKEMON Pikachu 2 3
./GameBoy BROKER CATCH_POKEMON Squirtle 5 2

./GameBoy BROKER CATCH_POKEMON Onix 4 5

./GameBoy SUSCRIPTOR CAUGHT_POKEMON 10

./GameBoy BROKER CATCH_POKEMON Vaporeon 4 5
