#!/bin/sh
./GameBoy TEAM APPEARED_POKEMON Pikachu 9 9
./GameBoy TEAM APPEARED_POKEMON Squirtle 6 7
./GameBoy TEAM APPEARED_POKEMON Onix 2 8
./GameBoy TEAM APPEARED_POKEMON Gengar 6 6
./GameBoy TEAM APPEARED_POKEMON Squirtle 5 5
